variables:
  MACOS_IMAGE: 'macos-12-xcode-14'

.package_template: &package_script
  stage: checks
  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 30 mins
    paths:
      - release/build

.deploy_template: &deploy_script
  stage: deploy
  only:
    - test-mac

  before_script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

  script:
    - aws s3 cp release/build/* s3://cdn.koii.live/$CURRENT_TARGET --acl public-read

install_macos:
  image: $MACOS_IMAGE
  script:
    - npm install
  tags:
    - shared-macos-amd64  
    
package_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  script:
    - npm run package
  tags:
    - shared-macos-amd64  

deploy_macos:
  image: $MACOS_IMAGE
  needs: ['package_macos']
  script:
    - npm install
  tags:
    - shared-macos-amd64    