variables:
  MACOS_IMAGE: 'macos-12-xcode-14'
  USE_HARD_LINKS: 'false'

.install_deps_template: &install_deps_script
  stage: prerequisites
  script:
    - npm install
  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 10 mins
    paths:
      - node_modules/

.lint_template: &lint_script
  stage: checks
  script:
    - npm run lint

.test_template: &test_script
  stage: checks
  script:
    - npm run test

.package_template: &package_script
  stage: checks

.deploy_template: &deploy_script
  stage: deploy
  only:
    - main

  before_script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

  script:
    - aws s3 cp release/build/* s3://cdn.koii.live/$CURRENT_TARGET --acl public-read

stages:
  - prerequisites
  - checks
  - deploy

install_macos:
  image: $MACOS_IMAGE
  <<: *install_deps_script
  tags:
    - shared-macos-amd64

lint_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  <<: *lint_script
  tags:
    - shared-macos-amd64

test_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  <<: *test_script
  tags:
    - shared-macos-amd64

package_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  <<: *package_script
  script:
    - npm run package
  tags:
    - shared-macos-amd64
  artifacts:
    paths:
      - 'release/build/*.zip'
      - 'release/build/*.dmg'

deploy_macos:
  image: $MACOS_IMAGE
  needs: ['package_macos']
  dependencies:
    - package_macos
  variables:
    CURRENT_TARGET: 'macos'
  <<: *deploy_script
  tags:
    - shared-macos-amd64 #mac