image: node:18.8.0

stages:
  - install
  - lint
  - build_deploy

install:
  stage: install
  script:
    - yarn install --cache-folder .yarn
  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 30 mins
    paths:
      - .yarn/
      - node_modules/

lint:
  stage: lint
  script:
    - yarn run lint
  dependencies:
    - install

build_deploy:
  stage: build_deploy

  only:
    - main
  
  before_script:
    - apt-get update -qq && apt-get install
    - apt -y install dpkg
    - apt update -y && apt upgrade -y
    - apt install fakeroot -y
    - apt-get install awscli -y
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

  script:
    - yarn make
    - ls -ltr out/make/deb/x64/
    - mkdir .public
    - cp -r out/make/deb/x64/* .public
    - mv .public public
    - ls -ltr public/
    - aws s3 cp public/* s3://cdn.koii.live --acl public-read   