variables:
  WINDOWS_IMAGE: 'electronuserland/builder:wine'
  LINUX_IMAGE: 'node:18.8.0'
  MACOS_IMAGE: 'macos-12-xcode-14'
  USE_HARD_LINKS: 'false'

include:
  - remote: https://gitlab.com/gitlab-org/incubation-engineering/devops-for-mobile-apps/demo-mobile-ci-templates/-/raw/main/Preinstall-Apple-WWDR-Certificates.gitlab-ci.yml

.install_deps_template: &install_deps_script
  stage: prerequisites
  script:
    - npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken=$GITLAB_ACCESS_TOKEN
    - npm config set @koii-network:registry https://gitlab.com/api/v4/packages/npm/
    - npm install
  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 10 mins
    paths:
      - node_modules/

.lint_template: &lint_script
  stage: checks
  script:
    - npm run lint

.test_template: &test_script
  stage: checks
  script:
    - npm run test

.package_template: &package_script
  stage: checks

stages:
  - prerequisites
  - checks

install_win:
  image: $WINDOWS_IMAGE
  <<: *install_deps_script

install_linux:
  image: $LINUX_IMAGE
  <<: *install_deps_script

install_macos:
  image: $MACOS_IMAGE
  before_script:
    - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew uninstall node@17
    - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install node@18
    - export PATH="/usr/local/opt/node@18/bin:$PATH"
    - export LDFLAGS="-L/usr/local/opt/node@18/lib"
    - export CPPFLAGS="-I/usr/local/opt/node@18/include"
  <<: *install_deps_script
  tags:
    - shared-macos-amd64

lint_win:
  image: $WINDOWS_IMAGE
  needs: ['install_win']
  dependencies:
    - install_win
  <<: *lint_script

lint_linux:
  image: $LINUX_IMAGE
  needs: ['install_linux']
  dependencies:
    - install_linux
  <<: *lint_script

lint_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  before_script:
    - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew uninstall node@17
    - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install node@18
    - export PATH="/usr/local/opt/node@18/bin:$PATH"
    - export LDFLAGS="-L/usr/local/opt/node@18/lib"
    - export CPPFLAGS="-I/usr/local/opt/node@18/include"
  <<: *lint_script
  tags:
    - shared-macos-amd64

test_win:
  image: $WINDOWS_IMAGE
  needs: ['install_win']
  dependencies:
    - install_win
  <<: *test_script

test_linux:
  image: $LINUX_IMAGE
  needs: ['install_linux']
  dependencies:
    - install_linux
  <<: *test_script

test_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  
  <<: *test_script
  tags:
    - shared-macos-amd64

package_win:
  image: $WINDOWS_IMAGE
  needs: ['install_win']
  dependencies:
    - install_win
  <<: *package_script
  script:
    - npm run package -- -w
  artifacts:
    paths:
      - 'release/build/*.exe'

package_linux:
  image: $LINUX_IMAGE
  needs: ['install_linux']
  dependencies:
    - install_linux
  <<: *package_script
  before_script:
    - apt-get update && apt-get install rpm -y
  script:
    - npm run package
  artifacts:
    paths:
      - 'release/build/*.AppImage'

package_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  before_script:
    - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew uninstall node@17
    - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install node@18
    - export PATH="/usr/local/opt/node@18/bin:$PATH"
    - export LDFLAGS="-L/usr/local/opt/node@18/lib"
    - export CPPFLAGS="-I/usr/local/opt/node@18/include"
  <<: *package_script
  script:
    - npm run package
  tags:
    - shared-macos-amd64
  artifacts:
    paths:
      - 'release/build/*.zip'
      - 'release/build/*.dmg'
