image: node:18.8.0

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - build
  - deploy

services:
  - docker:dind

build:
  stage: build
  before_script: 
    - npm install -g n
    - apt -y install dpkg
    - apt update -y && apt upgrade -y
    - apt install fakeroot -y
    - apt-get install awscli -y
    - aws configure set region $AWS_DEFAULT_REGION
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  script:
    - npx yarn
    - npx yarn make
    - ls -ltr out/make/deb/x64/
    - aws s3 cp /out/make/deb/x64/desktop-task-node_1.0.0_amd64.deb s3://packer-test11   

deploy:
  stage: deploy
  when: manual
  image:
    name: docker:latest
  dependencies:
    - build  
  before_script:
    - |
      apk add --no-cache curl jq python3 py3-pip
      pip install awscli
      aws configure set region $AWS_DEFAULT_REGION
      aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  
  script:
    - aws s3 cp /out/make/deb/x64/desktop-task-node_1.0.0_amd64.deb s3://packer-test11
