variables:
  WINDOWS_IMAGE: 'electronuserland/builder:wine'
  LINUX_IMAGE: 'node:18.8.0'
  MACOS_IMAGE: 'macos-12-xcode-14'

.install_deps_template: &install_deps_script
  stage: prerequisites
  script:
    - npm install
  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 30 mins
    paths:
      - node_modules/

.lint_template: &lint_script
  stage: checks
  script:
    - npm run lint

.test_template: &test_script
  stage: checks
  script:
    - npm run test

.package_template: &package_script
  stage: checks
  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 30 mins
    paths:
      - release/build

.deploy_template: &deploy_script
  stage: deploy
  only:
    - main

  before_script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

  script:
    - aws s3 cp release/build/* s3://cdn.koii.live/$CURRENT_TARGET --acl public-read

stages:
  - prerequisites
  - checks
  - deploy

install_macos:
  image: $MACOS_IMAGE
  <<: *install_deps_script
  tags:
    - shared-macos-amd64
  artifacts:
    paths:
      - 'release/build/*.zip'
      - 'release/build/*.dmg'    

lint_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  <<: *lint_script
  tags:
    - shared-macos-amd64

test_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  <<: *test_script
  tags:
    - shared-macos-amd64

package_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  <<: *package_script
  before_script:
  - npm ci --cache .npm --prefer-offline

  script:
#    - npm ci --cache .npm --prefer-offline
#    - rm -rf /Users/gitlab/builds/koii-network/desktop-node/release/app/node_modules/bufferutil/prebuilds/win32-x64/*
#    - rm -rf Users/gitlab/builds/koii-network/desktop-node/release/build/mac-arm64/Electron.app/Contents/Resources/app.asar.unpacked/node_modules/bufferutil/prebuilds/win32-x64/*
    - npm run package
  tags:
    - shared-macos-amd64

deploy_macos:
  image: $MACOS_IMAGE
  needs: ['package_macos']
  dependencies:
    - package_macos
  variables:
    CURRENT_TARGET: 'macos'
  <<: *deploy_script
  tags:
    - shared-macos-amd64