variables:
  WINDOWS_IMAGE: 'electronuserland/builder:wine-mono'
  LINUX_IMAGE: 'node:18.8.0'
  MACOS_IMAGE: 'macos-12-xcode-14'
  USE_HARD_LINKS: 'false'

cache:
  key:
    files:
      - package-lock.json
  paths:
    - .npm/

include:
  - remote: https://gitlab.com/gitlab-org/incubation-engineering/devops-for-mobile-apps/demo-mobile-ci-templates/-/raw/main/Preinstall-Apple-WWDR-Certificates.gitlab-ci.yml

stages:
  - prepare
  - checks
  - package

####################################################################################################
######################################## TEMPLATES #################################################
####################################################################################################

.brew_template: &brew
  before_script:
    - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew uninstall node@17
    - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install node@18
    - export PATH="/usr/local/opt/node@18/bin:$PATH"
    - export LDFLAGS="-L/usr/local/opt/node@18/lib"
    - export CPPFLAGS="-I/usr/local/opt/node@18/include"

.npm_ci_template: &npm_ci
  stage: prepare
  script:
    - npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken=$GITLAB_ACCESS_TOKEN
    - npm config set @koii-network:registry https://gitlab.com/api/v4/packages/npm/
    - npm ci --cache .npm --prefer-offline --no-audit --progress=false
  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 10 mins
    paths:
      - node_modules/

.lint_template: &lint
  stage: checks
  script:
    - npm run lint

.test_template: &test
  stage: checks
  script:
    - npm run test

####################################################################################################
######################################## PREPARE ###################################################
####################################################################################################

install_win:
  image: $WINDOWS_IMAGE
  <<: *npm_ci

install_linux:
  image: $LINUX_IMAGE
  <<: *npm_ci

install_macos:
  image: $MACOS_IMAGE
  <<: *brew
  <<: *npm_ci
  tags:
    - shared-macos-amd64

####################################################################################################
########################################## TEST ####################################################
####################################################################################################

lint_win:
  image: $WINDOWS_IMAGE
  needs: ['install_win']
  dependencies:
    - install_win
  <<: *lint

lint_linux:
  image: $LINUX_IMAGE
  needs: ['install_linux']
  dependencies:
    - install_linux
  <<: *lint

lint_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  <<: *brew
  <<: *lint
  tags:
    - shared-macos-amd64

test_win:
  image: $WINDOWS_IMAGE
  needs: ['install_win']
  dependencies:
    - install_win
  <<: *test

test_linux:
  image: $LINUX_IMAGE
  needs: ['install_linux']
  dependencies:
    - install_linux
  <<: *test

test_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  
  <<: *test
  tags:
    - shared-macos-amd64

####################################################################################################
######################################## PACKAGE ###################################################
####################################################################################################

package_win:
  image: $WINDOWS_IMAGE
  needs: ['install_win']
  dependencies:
    - install_win
  stage: package
  script:
    - npm run package -- -w
  artifacts:
    paths:
      - 'release/build/*.exe'

package_linux:
  image: $LINUX_IMAGE
  needs: ['install_linux']
  dependencies:
    - install_linux
  stage: package
  before_script:
    - apt-get update && apt-get install rpm -y
  script:
    - npm run package
  artifacts:
    paths:
      - 'release/build/*.AppImage'

package_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  <<: *brew
  stage: package
  script:
    - npm run package
  tags:
    - shared-macos-amd64
  artifacts:
    paths:
      - 'release/build/*.zip'
      - 'release/build/*.dmg'
