variables:
  LINUX_IMAGE: 'node:18.8.0'
  MACOS_IMAGE: 'macos-12-xcode-14'
  USE_HARD_LINKS: 'false'
  FF_USE_FASTZIP: 'true'
  TRANSFER_METER_FREQUENCY: 2s
  ARTIFACT_COMPRESSION_LEVEL: "fastest"
  CACHE_COMPRESSION_LEVEL: "fastest"
  DOCKER_DRIVER: overlay2

# Windows runners
.koii-windows-runner:
  tags:
  - koii-desktop-node-runner

stages:
  - prepare
  - checks
  - package

####################################################################################################
######################################## TEMPLATES #################################################
####################################################################################################

.brew_template: &brew
  before_script:
    - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew uninstall node@17
    - HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install node@18
    - export PATH="/usr/local/opt/node@18/bin:$PATH"
    - export LDFLAGS="-L/usr/local/opt/node@18/lib"
    - export CPPFLAGS="-I/usr/local/opt/node@18/include"

.npm_ci_template: &npm_ci
  stage: prepare
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_MERGE_REQUEST_ID'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
  script:
    - npm config set -- //gitlab.com/api/v4/packages/npm/:_authToken=$GITLAB_ACCESS_TOKEN
    - npm config set @koii-network:registry https://gitlab.com/api/v4/packages/npm/
    - npm ci --cache npm_cache --prefer-offline --no-audit --progress=false
  cache:
    - key: npm
      policy: pull-push
      paths:
        - npm_cache/
    - key: node_modules-${CI_COMMIT_REF_SLUG}
      policy: push
      paths:
        - node_modules/
        - release/app/node_modules/
        - src/node_modules/
  # artifacts:
  #   name: 'artifacts'
  #   untracked: false
  #   expire_in: 10 mins
  #   paths:
  #     - node_modules/
  #     - release/app/node_modules/
  #     - src/node_modules/

.lint_template: &lint
  stage: checks
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_MERGE_REQUEST_ID'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
  script:
    - npm run lint
  cache:
    - key: npm
      policy: pull
      paths:
        - npm_cache/
    - key: node_modules-${CI_COMMIT_REF_SLUG}
      policy: pull
      paths:
        - node_modules/
        - release/app/node_modules/
        - src/node_modules/

.test_template: &test
  stage: checks
  rules:
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$CI_MERGE_REQUEST_ID'
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
  script:
    - npm run test
  cache:
    - key: npm
      policy: pull
      paths:
        - npm_cache/
    - key: node_modules-${CI_COMMIT_REF_SLUG}
      policy: pull
      paths:
        - node_modules/
        - release/app/node_modules/
        - src/node_modules/

.package_rules_template: &package_rules
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
  stage: package

####################################################################################################
######################################## PREPARE ###################################################
####################################################################################################

install_win:
  extends:
    - .koii-windows-runner
  <<: *npm_ci

install_linux:
  image: $LINUX_IMAGE
  <<: *npm_ci

install_macos:
  image: $MACOS_IMAGE
  <<: *brew
  <<: *npm_ci
  tags:
    - shared-macos-amd64

####################################################################################################
########################################## TEST ####################################################
####################################################################################################

lint_win:
  extends:
    - .koii-windows-runner
  needs: ['install_win']
  dependencies:
    - install_win
  <<: *lint

lint_linux:
  image: $LINUX_IMAGE
  needs: ['install_linux']
  dependencies:
    - install_linux
  <<: *lint

lint_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  <<: *brew
  <<: *lint
  tags:
    - shared-macos-amd64

test_win:
  extends:
    - .koii-windows-runner
  needs: ['install_win']
  dependencies:
    - install_win
  <<: *test

test_linux:
  image: $LINUX_IMAGE
  needs: ['install_linux']
  dependencies:
    - install_linux
  <<: *test

test_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  
  <<: *test
  tags:
    - shared-macos-amd64

####################################################################################################
######################################## PACKAGE ###################################################
####################################################################################################

package_win:
  extends:
    - .koii-windows-runner
  needs: ['install_win']
  dependencies:
    - install_win
  <<: *package_rules
  script:
    - npm run release -- -w

package_linux:
  image: $LINUX_IMAGE
  needs: ['install_linux']
  dependencies:
    - install_linux
  <<: *package_rules
  before_script:
    - apt-get update && apt-get install rpm -y
  script:
    - npm run release

package_macos:
  image: $MACOS_IMAGE
  needs: ['install_macos']
  dependencies:
    - install_macos
  <<: *brew
  <<: *package_rules
  script:
    - npm run release
  tags:
    - shared-macos-amd64