image: node:18.8.0

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - build
  - deploy

build:
  stage: build
  
  before_script: 
    - npm install -g n
    - apt -y install dpkg
    - apt update -y && apt upgrade -y
    - apt install fakeroot -y
    - apt-get install awscli -y
    - aws configure set aws_access_key_id AKIAZDKCDTJQ63F47TNB
    - aws configure set aws_secret_access_key 4Pd7zwfKXI1bjk9SkyG6JMSmBXXACmxuBMTOZ/zc
    - aws configure set default_region_name "us-west-2"
    - aws configure set default_output_format "json"

  script:
    - npx yarn
    - npx yarn make
#    - aws s3 cp out/make/deb/* s3://packer-test11/ --recursive 
    #aws s3 cp out/make/deb/x64/desktop-task-node_1.0.0_amd64.deb s3://packer-test11      
    - ls -ltr out/make/deb/x64/
    - mkdir .public
    - cp -r out/make/deb/x64/* .public
    - mv .public public
  dependencies:
    - deploy
  artifacts:
    paths:
      - public/*.deb       

deploy:
  stage: deploy
  when: manual
  image:
    name: docker:latest
  dependencies:
    - build  
  before_script:
    - |
      apk add --no-cache curl jq python3 py3-pip
      pip install awscli
      aws configure set region $AWS_DEFAULT_REGION
      aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  
  script:
    - cd out/make/deb/x64/
    - npm i
    - npm run pack
    - aws s3 cp /out/make/deb/x64/desktop-task-node_1.0.0_amd64.deb s3://packer-test11

  artifacts:
    expire_in: 1 day
    paths:
      - out/make/deb/x64/*.deb    
