image: node:18.8.0

stages:
  - prerequisites
  - checks
  - deploy

install:
  stage: prerequisites
  script:
    - npm install

  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 30 mins
    paths:
      - node_modules/

lint:
  stage: checks
  needs: ['install']

  script:
    - npm run lint

test:
  stage: checks
  needs: ['install']

  script:
    - npm run test
  dependencies:
    - install

build:
  stage: checks
  needs: ['install']

  script:
    - npm run package
  artifacts:
    name: 'artifacts'
    untracked: true
    expire_in: 30 mins
    paths:
      - release/build
  dependencies:
    - install

deploy:
  stage: deploy
  needs: ['build']
  only:
    - main

  before_script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

  script:
    - aws s3 cp release/build/* s3://cdn.koii.live --acl public-read
