image: node:16.3.0-alpine

before_script:  
  - apt-get update -qq && apt-get install

stages:
  - build
  - deploy

Build:
  stage: build
  before_script: 
    - npm install -g n
  script:
    - npx yarn
    - npx yarn make

deploy:
  stage: deploy
  image:
    name: amazon/awscli
  before_script:
    - |
      aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      aws configure set region $AWS_DEFAULT_REGION
  
  script:
    - aws configure set region $AWS_DEFAULT_REGION
    - aws s3 cp desktop-task-node_1.0.0_amd64.deb s3://packer-test11