export enum QueryKeys {
  taskList = 'taskList',
  availableTaskList = 'availableTaskList',
  myTaskList = 'myTaskList',
  taskReward = 'taskReward',
  mainAccountBalance = 'mainAccountBalance',
  taskSourceCode = 'taskSourceCode',
  taskNodeInfo = 'taskNodeInfo',
  UserSettings = 'UserSettings',
  MainAccount = 'MainAccount',
  StakingAccount = 'StakingAccount',
  Accounts = 'Accounts',
  TaskStake = 'TaskStake',
  TaskVariables = 'TaskVariables',
  TaskVariablesNames = 'TaskVariablesNames',
  StoredTaskVariables = 'StoredTaskVariables',
  StoredPairedTaskVariables = 'StoredPairedTaskVariables',
  TasksPairedWithVariable = 'TasksPairedWithVariable',
  StoredTaskPairedTaskVariables = 'StoredTaskPairedTaskVariables',
  TaskMetadata = 'TaskMetadata',
  GetNetworkUrl = 'GetNetworkUrl',
  NodeInitialized = 'NodeInitialized',
}
