const GET_TASKS = 'GET_TASKS';
const GET_TASK_SOURCE = 'GET_TASK_SOURCE';
const DELEGATE_STAKE = 'DELEGATE_STAKE';
const GET_TASK_INFO = 'GET_TASK_INFO';
const START_TASK = 'START_TASK';
const STOP_TASK = 'STOP_TASK';
const GET_EARNED_REWARD_BY_NODE = 'GET_EARNED_REWARD_BY_NODE';
const CHECK_WALLET_EXISTS = 'CHECK_WALLET_EXISTS';
const GET_MAIN_ACCOUNT_PUBKEY = 'GET_MAIN_ACCOUNT_PUBKEY';
const GET_STAKING_ACCOUNT_PUBKEY = 'GET_STAKING_ACCOUNT_PUBKEY';
const GET_TASK_LOGS = 'GET_TASK_LOGS';
const GET_MY_TASKS = 'GET_MY_TASKS';
const GET_AVAILABLE_TASKS = 'GET_AVAILABLE_TASKS';
const WITHDRAW_STAKE = 'WITHDRAW_STAKE';
const CREATE_NODE_WALLETS = 'CREATE_NODE_WALLETS';

export default {
  GET_TASKS,
  GET_TASK_SOURCE,
  DELEGATE_STAKE,
  GET_TASK_INFO,
  START_TASK,
  STOP_TASK,
  GET_EARNED_REWARD_BY_NODE,
  CHECK_WALLET_EXISTS,
  GET_MAIN_ACCOUNT_PUBKEY,
  GET_TASK_LOGS,
  GET_STAKING_ACCOUNT_PUBKEY,
  GET_MY_TASKS,
  GET_AVAILABLE_TASKS,
  WITHDRAW_STAKE,
  CREATE_NODE_WALLETS,
};
