const GET_TASKS = 'GET_TASKS';
const GET_TASK_SOURCE = 'GET_TASK_SOURCE';
const CREATE_STAKING_WALLET = 'CREATE_STAKING_WALLET';
const DELEGATE_STAKE = 'DELEGATE_STAKE';
const GET_TASK_INFO = 'GET_TASK_INFO';
const START_TASK = 'START_TASK';
const STOP_TASK = 'STOP_TASK';
const STORE_MAIN_WALLET = 'STORE_MAIN_WALLET';
const REWARD_WALLET = 'REWARD_WALLET';
const CHECK_WALLET = 'CHECK_WALLET';
export default {
  GET_TASKS,
  GET_TASK_SOURCE,
  CREATE_STAKING_WALLET,
  DELEGATE_STAKE,
  GET_TASK_INFO,
  START_TASK,
  STOP_TASK,
  STORE_MAIN_WALLET,
  REWARD_WALLET,
  CHECK_WALLET,
};
