const GET_TASKS = 'GET_TASKS';
const GET_TASK_SOURCE = 'GET_TASK_SOURCE';
const CREATE_WALLET = 'CREATE_WALLET';
const DELEGATE_STAKE = 'DELEGATE_STAKE';
const GET_TASK_INFO = 'GET_TASK_INFO';
const START_TASK = 'START_TASK';
const STOP_TASK = 'STOP_TASK';
const STORE_WALLET = 'STORE_WALLET';
const REWARD_WALLET = 'REWARD_WALLET';
export default {
  GET_TASKS,
  GET_TASK_SOURCE,
  CREATE_WALLET,
  DELEGATE_STAKE,
  GET_TASK_INFO,
  START_TASK,
  STOP_TASK,
  STORE_WALLET,
  REWARD_WALLET,
};
