export enum QueryKeys {
  taskList = 'taskList',
  availableTaskList = 'availableTaskList',
  myTaskList = 'myTaskList',
  taskReward = 'taskReward',
  mainAccountBalance = 'mainAccountBalance',
  minStake = 'minStake',
  taskSourceCode = 'taskSourceCode',
  taskNodeInfo = 'taskNodeInfo',
  UserSettings = 'UserSettings',
  MainAccount = 'MainAccount',
  Accounts = 'Accounts',
  TaskStake = 'TaskStake',
  TaskVariables = 'TaskVariables',
  TaskVariablesNames = 'TaskVariablesNames',
  StoredTaskVariables = 'StoredTaskVariables',
}
